import asyncio
import os
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any

import pytest
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

_llm_configured = bool(os.getenv("PRAXIS_LLM_API_KEY") or os.getenv("LLM_API_KEY") or os.getenv("OPENAI_API_KEY"))

from app.api import functions as functions_api
from app.api import schedules as schedules_api
from app.db.database import Base
from app.models import models
from app.services.agent.build_verify_loop import (
    ReflectionDecision,
    BuildAttempt,
    BuildVerifyLoop,
    VerificationOutcome,
)
from app.services.platform.coding_engine import CodingEngineApplyResult


class _FakeFunctionWorkspaceStore:
    def set_adapter_event_callback(self, _callback):
        return None

    def sync_function_draft(self, function: models.Function):
        path = Path("/tmp/praxis-test-fake/functions") / str(function.id or 0) / "main.py"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(str(function.draft_code or ""), encoding="utf-8")
        return path

    def commit_publish(self, *, object_type: str, object_id: int, action: str, summary: str | None = None):
        _ = object_type, object_id, action, summary
        return "fake-commit-sha"

    def analyze_function_goal(self, *, function: models.Function, stage_prompt: str, datasource_schema=None, datasource_id=None):
        _ = function, stage_prompt, datasource_schema, datasource_id
        return CodingEngineApplyResult(
            changed_files=[],
            diff_summary="",
            tests_suggested=[],
            risk_notes=[],
            assistant_message="需求分析完成，可以继续构建。",
            result_status="clear",
        )

    def apply_function_goal(self, *, function: models.Function, goal: str, datasource_schema=None, datasource_id=None):
        _ = goal, datasource_schema, datasource_id
        function.draft_code = "def main(payload, context):\n    return {'ok': True, 'from_engine': True}\n"
        function.draft_dependencies = {}
        return CodingEngineApplyResult(
            changed_files=["main.py"],
            diff_summary="updated function draft",
            tests_suggested=[],
            risk_notes=[],
            assistant_message="Function 草稿已通过 coding engine 更新。",
        )


class _FakePageWorkspaceStore:
    def sync_page_draft(self, page: models.Page):
        path = Path("/tmp/praxis-test-fake/pages") / str(page.id or 0) / "main.tsx"
        path.parent.mkdir(parents=True, exist_ok=True)
        source = (page.draft_payload or {}).get("source") or {}
        path.write_text(str(source.get("code") or ""), encoding="utf-8")
        return path

    def apply_page_goal(self, *, page: models.Page, goal: str):
        _ = goal
        page.draft_payload = {
            "version": "page-runtime-v2",
            "config": {"title": "Engine Page", "description": "generated by coding engine"},
            "source": {"language": "tsx", "code": "export default function Page(){return <main>engine</main>}"},
            "runtime": {
                "framework": "html",
                "preview_html": "<!doctype html><html><body><main>engine</main></body></html>",
            },
            "meta": {"updated_at": "", "last_prompt": "", "summary": "", "plan": {"goal": "", "todos": []}, "history": []},
        }
        return CodingEngineApplyResult(
            changed_files=["main.tsx"],
            diff_summary="updated page draft",
            tests_suggested=[],
            risk_notes=[],
            assistant_message="Page 草稿已通过 coding engine 更新。",
        )


class _RetryingFunctionWorkspaceStore(_FakeFunctionWorkspaceStore):
    calls = 0

    @classmethod
    def reset(cls) -> None:
        cls.calls = 0

    def apply_function_goal(self, *, function: models.Function, goal: str, datasource_schema=None, datasource_id=None):
        _ = goal, datasource_schema, datasource_id
        type(self).calls += 1
        if type(self).calls == 1:
            function.draft_code = (
                "def main(payload, context):\n"
                "    query_result = db.query('SHOW DATABASES', datasource=1)\n"
                "    return {'rows': [row[0] for row in query_result]}\n"
            )
        else:
            function.draft_code = (
                "def main(payload, context):\n"
                "    result = db.query('SHOW DATABASES', datasource=1)\n"
                "    rows = result.get('rows', [])\n"
                "    names = []\n"
                "    for row in rows:\n"
                "        names.append(row.get('Database') or row.get('database') or '')\n"
                "    return {'names': [item for item in names if item]}\n"
            )
        function.draft_dependencies = {}
        return CodingEngineApplyResult(
            changed_files=["main.py"],
            diff_summary=f"retry-{type(self).calls}",
            tests_suggested=[],
            risk_notes=[],
            assistant_message=f"attempt-{type(self).calls}",
        )


class _RetryingPageWorkspaceStore(_FakePageWorkspaceStore):
    calls = 0

    @classmethod
    def reset(cls) -> None:
        cls.calls = 0

    def apply_page_goal(self, *, page: models.Page, goal: str):
        _ = goal
        type(self).calls += 1
        preview = ""
        if type(self).calls > 1:
            preview = "<!doctype html><html><body><main>retry-ok</main></body></html>"
        page.draft_payload = {
            "version": "page-runtime-v2",
            "config": {"title": "Engine Page", "description": "generated by coding engine"},
            "source": {"language": "tsx", "code": "export default function Page(){return <main>retry</main>}"},
            "runtime": {
                "framework": "html",
                "preview_html": preview,
            },
            "meta": {"updated_at": "", "last_prompt": "", "summary": "", "plan": {"goal": "", "todos": []}, "history": []},
        }
        return CodingEngineApplyResult(
            changed_files=["main.tsx"],
            diff_summary=f"retry-{type(self).calls}",
            tests_suggested=[],
            risk_notes=[],
            assistant_message=f"attempt-{type(self).calls}",
        )


class _FailingFunctionWorkspaceStore(_FakeFunctionWorkspaceStore):
    def apply_function_goal(self, *, function: models.Function, goal: str, datasource_schema=None, datasource_id=None):
        _ = function, goal, datasource_schema, datasource_id
        raise ValueError("pi-lite reached max_steps=10 without final JSON response")


class _NoopFunctionWorkspaceStore(_FakeFunctionWorkspaceStore):
    def apply_function_goal(self, *, function: models.Function, goal: str, datasource_schema=None, datasource_id=None):
        _ = function, goal, datasource_schema, datasource_id
        return CodingEngineApplyResult(
            changed_files=[],
            diff_summary="No effective changes",
            tests_suggested=[],
            risk_notes=[],
            assistant_message="我检查了逻辑并已修复。",
        )


class _InvalidFunctionWorkspaceStore(_FakeFunctionWorkspaceStore):
    def apply_function_goal(self, *, function: models.Function, goal: str, datasource_schema=None, datasource_id=None):
        _ = function, goal, datasource_schema, datasource_id
        function.draft_code = (
            "def main(payload, context):\n"
            "    query_result = db.query('SHOW DATABASES', datasource=1)\n"
            "    rows = query_result.get('rows', [])\n"
            "    names = [row[0] for row in rows]\n"
            "    return {'names': names}\n"
        )
        function.draft_dependencies = {}
        return CodingEngineApplyResult(
            changed_files=["main.py"],
            diff_summary="updated function draft",
            tests_suggested=[],
            risk_notes=[],
            assistant_message="我检查了逻辑并已修复。",
        )


class _SchedulerHistoryCleanupWorkspaceStore(_FakeFunctionWorkspaceStore):
    def apply_function_goal(self, *, function: models.Function, goal: str, datasource_schema=None, datasource_id=None):
        _ = goal, datasource_schema, datasource_id
        function.draft_code = (
            "def main(payload, context):\n"
            "    return scheduler_history.delete(\n"
            "        where={'schedule_id': int(payload['target_schedule_id'])},\n"
            "        policy={'retention_seconds': int(payload.get('retention_seconds', 30 * 24 * 3600))},\n"
            "        dry_run=bool(payload.get('dry_run', False)),\n"
            "    )\n"
        )
        function.draft_dependencies = {}
        return CodingEngineApplyResult(
            changed_files=["main.py"],
            diff_summary="updated function draft for scheduler history cleanup",
            tests_suggested=["先用 dry_run=True 测试，再发布并绑定 Scheduler"],
            risk_notes=[],
            assistant_message="Function 草稿已更新为 Scheduler 历史清理逻辑。",
        )


def _session_factory(tmp_path: Path):
    db_path = tmp_path / "runtime-object-api-coding-engine.db"
    engine = create_engine(f"sqlite:///{db_path}")
    Base.metadata.create_all(engine)
    factory = sessionmaker(bind=engine, autocommit=False, autoflush=False, expire_on_commit=False)
    return factory, engine


def test_function_build_retries_until_verification_pass(tmp_path: Path, monkeypatch: pytest.MonkeyPatch):
    _RetryingFunctionWorkspaceStore.reset()
    monkeypatch.setattr(functions_api, "WorkspaceStore", _RetryingFunctionWorkspaceStore)
    session_factory, engine = _session_factory(tmp_path)
    db = session_factory()
    try:
        function = functions_api.create_function({"name": "retry-function", "draft_code": ""}, db=db)
        built = functions_api.build_function(
            function["id"],
            {"prompt": "按租户统计采集状态并返回明细"},
            db=db,
        )
        assert built["build_run"]["status"] == "done"
        events = built["build_run"]["events"]
        assert events
        payload = events[0].get("payload") or {}
        attempts = payload.get("attempts") if isinstance(payload.get("attempts"), list) else []
        schema_probe = payload.get("schema_probe") if isinstance(payload.get("schema_probe"), dict) else {}
        assert len(attempts) >= 2
        assert attempts[0].get("status") == "failed"
        assert "ran" in schema_probe
        assert _RetryingFunctionWorkspaceStore.calls >= 2
    finally:
        db.close()
        engine.dispose()


def test_agent_runtime_kernel_handles_complex_task_catalog():
    class _StubReflectionPlanner:
        def decide(
            self,
            *,
            scope: str,
            initial_goal: str,
            current_goal: str,
            attempt_index: int,
            max_attempts: int,
            diagnostics: list[str],
            error: str,
            attempts: list[BuildAttempt],
        ) -> ReflectionDecision:
            _ = scope, current_goal, diagnostics, error, attempts
            if attempt_index >= max_attempts:
                return ReflectionDecision(action="needs_clarification", reason="max_attempts_exhausted")
            return ReflectionDecision(
                action="retry",
                reason="stub_retry",
                next_goal=f"{initial_goal}\nRetry attempt {attempt_index + 1}: 调整数据源并重试",
                missing=[],
            )

    scenarios = [
        "统计信息采集健康总览：按集群/租户筛选，展示趋势与问题表",
        "慢 SQL 治理：按实例筛选，展示 TopN 与 P95 趋势",
        "备份可用性巡检：展示成功率、失败分布与高风险租户",
    ]

    for scenario in scenarios:
        counter = {"value": 0}
        kernel = BuildVerifyLoop(max_attempts=3, reflection_planner=_StubReflectionPlanner())

        def _verify(build_result: Any, goal: str, attempt_index: int, attempts: list[BuildAttempt]) -> VerificationOutcome:
            _ = build_result, goal, attempt_index, attempts
            counter["value"] += 1
            passed = counter["value"] >= 2
            return VerificationOutcome(
                passed=passed,
                diagnostics=[] if passed else ["schema_mismatch", "field_missing"],
                payload={"passed": passed},
                summary="ok" if passed else "retry",
            )

        result = kernel.run(
            scope="function.build",
            initial_goal=scenario,
            build_step=lambda goal, attempt_index, attempts: {"attempt": attempt_index, "goal": goal},
            verify_step=_verify,
        )
        assert result.status == "done"
        assert len(result.attempts) >= 2


def test_function_create_enters_with_temporary_name_then_first_build_generates_metadata(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
):
    class _FakeMetadataLLM:
        async def chat(self, *args: Any, **kwargs: Any):
            _ = args, kwargs
            yield {
                "choices": [
                    {
                        "message": {
                            "content": '{"title":"历史记录清理","description":"用于清理过期的 Scheduler 运行历史。"}'
                        }
                    }
                ]
            }

    monkeypatch.setattr(functions_api, "WorkspaceStore", _FakeFunctionWorkspaceStore)
    monkeypatch.setattr(functions_api, "get_llm_client", lambda: _FakeMetadataLLM())
    session_factory, engine = _session_factory(tmp_path)
    db = session_factory()
    try:
        created = functions_api.create_function({}, db=db)
        assert created["name"].startswith("未命名 Function")
        assert created["description"] is None

        built = functions_api.build_function(created["id"], {"prompt": "清理每天产生的历史记录"}, db=db)
        assert built["function"]["name"] == "历史记录清理"
        assert built["function"]["description"] == "用于清理过期的 Scheduler 运行历史。"

        updated = functions_api.update_function(
            created["id"],
            {"name": "用户自定义函数名", "description": "用户手动描述"},
            db=db,
        )
        assert updated["name"] == "用户自定义函数名"
        assert updated["description"] == "用户手动描述"

        rebuilt = functions_api.build_function(created["id"], {"prompt": "再改一下实现，但不要覆盖标题"}, db=db)
        assert rebuilt["function"]["name"] == "用户自定义函数名"
        assert rebuilt["function"]["description"] == "用户手动描述"
    finally:
        db.close()
        engine.dispose()


def test_function_chat_build_with_coding_engine_mode(tmp_path: Path, monkeypatch: pytest.MonkeyPatch):
    monkeypatch.setattr(functions_api, "WorkspaceStore", _FakeFunctionWorkspaceStore)
    session_factory, engine = _session_factory(tmp_path)
    db = session_factory()
    try:
        function = functions_api.create_function({"name": "engine-function", "draft_code": ""}, db=db)
        response = asyncio.run(
            functions_api.run_function_chat_action(
                function["id"],
                {"action": "build", "prompt": "给我一个返回 ok 的函数", "build_mode": "coding_engine"},
                db=db,
            )
        )
        assert response["status"] == "done"
        assert response["data"]["build_run"]["phase"] == "apply"
        assert response["assistant_message"] == "Function 草稿已更新，请在测试面板验证业务结果。"
        assert "from_engine" in str(response["data"]["function"]["draft_code"] or "")
    finally:
        db.close()
        engine.dispose()


def test_function_chat_build_with_coding_engine_mode_returns_failed_instead_of_500(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
):
    monkeypatch.setattr(functions_api, "WorkspaceStore", _FailingFunctionWorkspaceStore)
    session_factory, engine = _session_factory(tmp_path)
    db = session_factory()
    try:
        function = functions_api.create_function({"name": "engine-function-failed", "draft_code": ""}, db=db)
        response = asyncio.run(
            functions_api.run_function_chat_action(
                function["id"],
                {"action": "build", "prompt": "给我一个返回 ok 的函数", "build_mode": "coding_engine"},
                db=db,
            )
        )
        assert response["status"] == "failed"
        assert response["data"]["build_run"]["status"] == "failed"
        assert "max_steps=10" in str(response["assistant_message"] or "")
    finally:
        db.close()
        engine.dispose()


def test_function_chat_build_with_coding_engine_mode_reports_no_change(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
):
    monkeypatch.setattr(functions_api, "WorkspaceStore", _NoopFunctionWorkspaceStore)
    session_factory, engine = _session_factory(tmp_path)
    db = session_factory()
    try:
        function = functions_api.create_function(
            {
                "name": "engine-function-no-change",
                "description": "original description",
                "draft_code": "def main(payload, context):\n    return {'ok': True}\n",
            },
            db=db,
        )
        response = asyncio.run(
            functions_api.run_function_chat_action(
                function["id"],
                {"action": "build", "prompt": "修复输出问题", "build_mode": "coding_engine"},
                db=db,
            )
        )
        assert response["status"] == "done"
        assert "未检测到 `main.py` 实际变更" in str(response["assistant_message"] or "")
        assert response["data"]["function"]["description"] == "original description"
        events = response["data"]["build_run"]["events"]
        assert events
        payload = events[0].get("payload") or {}
        assert payload.get("no_changes_applied") is True
    finally:
        db.close()
        engine.dispose()


def test_function_chat_build_with_invalid_generated_code_returns_verification_failed(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
):
    monkeypatch.setattr(functions_api, "WorkspaceStore", _InvalidFunctionWorkspaceStore)
    session_factory, engine = _session_factory(tmp_path)
    db = session_factory()
    try:
        function = functions_api.create_function({"name": "engine-function-invalid", "draft_code": ""}, db=db)
        response = asyncio.run(
            functions_api.run_function_chat_action(
                function["id"],
                {"action": "build", "prompt": "给我数据库列表函数", "build_mode": "coding_engine"},
                db=db,
            )
        )
        assert response["status"] == "failed"
        assert response["data"]["build_run"]["status"] == "failed"
        assert "未通过契约校验" in str(response["assistant_message"] or "")
        assert "db.query" in str(response["assistant_message"] or "")
        assert str(response["data"]["function"]["draft_code"] or "") == ""
        workspace_main = Path("/tmp/praxis-test-fake/functions") / str(function["id"]) / "main.py"
        assert workspace_main.exists()
        assert workspace_main.read_text(encoding="utf-8") == ""
    finally:
        db.close()
        engine.dispose()


@pytest.mark.skipif(not _llm_configured, reason="requires LLM API key")
def test_function_build_end_to_end_scheduler_history_cleanup(tmp_path: Path, monkeypatch: pytest.MonkeyPatch):
    monkeypatch.setattr(functions_api, "WorkspaceStore", _SchedulerHistoryCleanupWorkspaceStore)
    session_factory, engine = _session_factory(tmp_path)
    db = session_factory()
    try:
        target_schedule = models.Schedule(
            name="history-target",
            status="active",
            target_type="function",
            target_id=999,
            schedule_type="interval",
            interval_seconds=3600,
            timezone="UTC",
        )
        db.add(target_schedule)
        db.flush()
        stale_run = models.ScheduleRun(
            schedule_id=target_schedule.id,
            run_id="target-stale",
            status="success",
            trigger_type="scheduled",
            attempt=1,
            retry_count=0,
            max_retries=0,
            created_at=datetime.utcnow() - timedelta(days=45),
        )
        fresh_run = models.ScheduleRun(
            schedule_id=target_schedule.id,
            run_id="target-fresh",
            status="success",
            trigger_type="scheduled",
            attempt=1,
            retry_count=0,
            max_retries=0,
            created_at=datetime.utcnow() - timedelta(days=5),
        )
        db.add_all([stale_run, fresh_run])
        db.commit()

        function = functions_api.create_function({"name": "调度历史清理"}, db=db)
        built = functions_api.build_function(
            function["id"],
            {"prompt": "构建一个 Function，清理 30 天前的 Scheduler 运行历史，先 dry-run 验证"},
            db=db,
        )
        assert built["build_run"]["status"] == "done"
        assert "scheduler_history.delete" in str(built["function"]["draft_code"] or "")

        draft_run = asyncio.run(
            functions_api.invoke_function(
                function["id"],
                {
                    "payload": {
                        "target_schedule_id": target_schedule.id,
                        "retention_seconds": 30 * 24 * 3600,
                        "dry_run": True,
                    },
                    "runtime_path": "draft",
                    "execution_mode": "plan",
                    "write_mode": "readonly",
                },
                db=db,
            )
        )
        assert draft_run["status"] == "success"
        assert draft_run["output"]["dry_run"] is True
        assert draft_run["output"]["candidate_count"] == 1

        unchanged_run_ids = {
            row.run_id
            for row in db.query(models.ScheduleRun)
            .filter(models.ScheduleRun.schedule_id == target_schedule.id)
            .all()
        }
        assert "target-stale" in unchanged_run_ids
        assert "target-fresh" in unchanged_run_ids

        released = functions_api.release_function(function["id"], {}, db=db)
        assert released["function"]["status"] == "released"

        cleanup_schedule = schedules_api.create_schedule(
            {
                "name": "cleanup-history-daily",
                "function_id": function["id"],
                "schedule_type": "interval",
                "interval_seconds": 86400,
                "input_payload": {
                    "target_schedule_id": target_schedule.id,
                    "retention_seconds": 30 * 24 * 3600,
                    "dry_run": False,
                },
            },
            db=db,
        )
        run_now = asyncio.run(schedules_api.run_schedule_now(cleanup_schedule["id"], db=db))
        assert isinstance(run_now["run_id"], str)

        target_run_ids_after = {
            row.run_id
            for row in db.query(models.ScheduleRun)
            .filter(models.ScheduleRun.schedule_id == target_schedule.id)
            .all()
        }
        assert "target-stale" not in target_run_ids_after
        assert "target-fresh" in target_run_ids_after

        cleanup_runs = schedules_api.list_schedule_runs(cleanup_schedule["id"], db=db)
        assert cleanup_runs
        latest_cleanup = cleanup_runs[0]
        assert latest_cleanup["status"] == "success"
        output_payload = latest_cleanup.get("output_payload") if isinstance(latest_cleanup.get("output_payload"), dict) else {}
        assert output_payload.get("deleted_count") == 1
    finally:
        db.close()
        engine.dispose()


def test_function_build_chat_invoke_hides_runtime_mode_terms_from_user_message(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
):
    monkeypatch.setattr(functions_api, "WorkspaceStore", _SchedulerHistoryCleanupWorkspaceStore)
    session_factory, engine = _session_factory(tmp_path)
    db = session_factory()
    try:
        schedule = models.Schedule(
            name="history-target",
            status="active",
            target_type="function",
            target_id=999,
            schedule_type="interval",
            interval_seconds=3600,
            timezone="UTC",
        )
        db.add(schedule)
        db.flush()
        db.add(
            models.ScheduleRun(
                schedule_id=schedule.id,
                run_id="target-stale",
                status="success",
                trigger_type="scheduled",
                attempt=1,
                retry_count=0,
                max_retries=0,
                created_at=datetime.utcnow() - timedelta(days=45),
            )
        )
        db.commit()

        function = functions_api.create_function({"name": "调度历史清理"}, db=db)
        functions_api.build_function(
            function["id"],
            {"prompt": "构建一个 Function，清理 30 天前的 Scheduler 运行历史，先 dry-run 验证"},
            db=db,
        )

        preview_response = asyncio.run(
            functions_api.run_function_chat_action(
                function["id"],
                {
                    "action": "invoke",
                    "invoke": {
                        "payload": {
                            "target_schedule_id": schedule.id,
                            "retention_seconds": 30 * 24 * 3600,
                            "dry_run": True,
                        },
                        "runtime_path": "draft",
                        "execution_mode": "plan",
                        "write_mode": "readonly",
                    },
                },
                db=db,
            )
        )
        assert preview_response["status"] == "success"
        assert preview_response["assistant_message"] == "已完成历史清理预演，命中 1 条记录。"
        assert "execution_mode" not in (preview_response.get("data") or {})
        assert "runtime_path" not in (preview_response.get("data") or {})
        assert "write_mode" not in (preview_response.get("data") or {})

        blocked_response = asyncio.run(
            functions_api.run_function_chat_action(
                function["id"],
                {
                    "action": "invoke",
                    "invoke": {
                        "payload": {
                            "target_schedule_id": schedule.id,
                            "retention_seconds": 30 * 24 * 3600,
                            "dry_run": False,
                        },
                        "runtime_path": "draft",
                        "execution_mode": "plan",
                        "write_mode": "readonly",
                    },
                },
                db=db,
            )
        )
        assert blocked_response["status"] == "failed"
        assert "当前测试执行仅支持预演" in str(blocked_response["assistant_message"] or "")
        assert "execution_mode" not in str(blocked_response["assistant_message"] or "")
    finally:
        db.close()
        engine.dispose()


@pytest.mark.skipif(not _llm_configured, reason="requires LLM API key")
def test_compose_function_engine_goal_uses_previous_requirement_for_retry_prompt():
    type_error_text = "TypeError: main() takes 1 positional argument" + " but 2 were given"
    missing_module_text = "ModuleNotFoundError: No module named " + "'praxis'"
    goal = functions_api._compose_function_engine_goal(  # type: ignore[attr-defined]
        "再次构建",
        recent_contexts=[
            {
                "prompt": "入参是个数，根据个数返回 datasource 列表",
                "status": "failed",
                "error": type_error_text,
                "summary": "Function 构建失败",
            },
            {
                "prompt": "根据 datasource_id 查询库名",
                "status": "failed",
                "error": missing_module_text,
                "summary": "Function 构建失败",
            },
        ],
        conversation_context="user: 再次构建\nassistant: 上次构建失败，正在修复",
    )
    assert "Primary Requirement:\n入参是个数，根据个数返回 datasource 列表" in goal
    assert f"Previous Build Error:\n{type_error_text}" in goal
    assert "Current Build Conversation (latest turns):\nuser: 再次构建" in goal
    assert "Recent Build Attempts (newest->older):" in goal
    assert "Do not return mock/fake/placeholder datasource data" in goal
    assert "Fixed Runtime Contract (JSON):" in goal


