"""Cross-entrypoint contract using the real worker and a deterministic SDK model.

Agent configuration is explicitly submitted by the user, not claimed to have
been generated by a model. Real-model behavior is tested separately via HTTP.
"""

import json

from test_custom_agents import create, custom_app, finish  # noqa: F401
from test_runtime import Script, call
from test_scheduler import wait_status

from app.api import schedules as schedules_api
from app.services.agent.scheduled_runner import ScheduledAgentRunner
from app.services.scheduler.worker import SchedulerWorker


async def test_chat_configured_agent_and_schedule_share_native_history_and_execution(
    custom_app,  # noqa: F811
    monkeypatch,
):
    runtime, client = custom_app
    script = Script(
        ["请明确选择 Agent 可以使用的工具和数据源。"],
        ["配置限定为 source-1，只允许列出数据源。"],
        [call("list_datasources")],
        ["可访问 source-1。"],
        [call("list_datasources")],
        ["本次定时查询返回 source-1。"],
    )
    runtime.service.model_factory = script.factory
    response = await client.post("/api/v1/conversations", json={"scene": {"datasource_ids": [1]}})
    assert response.status_code == 201
    source_id = response.json()["id"]
    for index, prompt in enumerate(
        ("帮我整理一个只读 Agent 的配置", "仅用 list_datasources，限定 source-1")
    ):
        submitted = await client.post(
            f"/api/v1/conversations/{source_id}/runs",
            json={
                "client_request_id": f"chat-{index}",
                "prompt": prompt,
            },
        )
        assert submitted.status_code == 202
        await finish(runtime, submitted.json()["id"])
    assert len(script.requests[1][0]) > len(script.requests[0][0])

    agent = await create(client, prompt="仅列出被授权的数据源，不修改任何数据。")
    conversation = await client.post(
        "/api/v1/conversations", json={"scene": {"agent_id": agent["id"]}}
    )
    assert conversation.status_code == 201
    submitted = await client.post(
        f"/api/v1/conversations/{conversation.json()['id']}/runs",
        json={
            "client_request_id": "agent-run",
            "prompt": "执行查询",
        },
    )
    assert submitted.status_code == 202
    manual = await finish(runtime, submitted.json()["id"])
    assert manual["definition"]["scope"]["datasource_ids"] == [1]
    assert [item["id"] for item in manual["tool_calls"][0]["result"]["content"]] == [1]

    worker = SchedulerWorker(
        session_factory=runtime.sessions, agent_runtime_service=ScheduledAgentRunner(runtime)
    )
    monkeypatch.setattr(schedules_api, "get_scheduler_worker", lambda: worker)
    try:
        schedule = await client.post(
            "/api/v1/schedules",
            json={
                "name": "native agent schedule",
                "target_type": "agent",
                "target_id": agent["id"],
                "schedule_type": "interval",
                "interval_seconds": 3600,
                "input_prompt": "执行查询",
                "max_retries": 0,
            },
        )
        assert schedule.status_code == 201, schedule.text
        schedule_id = schedule.json()["id"]
        submitted = await client.post(f"/api/v1/schedules/{schedule_id}/run-now")
        assert submitted.status_code == 200, submitted.text
        occurrence = await wait_status(runtime, submitted.json()["run_id"], "finished")
        native = runtime.store.get(occurrence["runtime_run_id"], "local")
        assert native["definition"]["tool_names"] == manual["definition"]["tool_names"]
        assert native["definition"]["scope"]["datasource_ids"] == [1]
        assert native["definition"]["scope"]["entrypoint"] == "scheduler"
        assert native["tool_calls"][0]["result"] == manual["tool_calls"][0]["result"]
        history = await client.get(f"/api/v1/schedules/{schedule_id}/runs")
        assert any(
            row["runtime_run_id"] == native["id"] and row["status"] == "finished"
            for row in history.json()
        )
        for row in (manual, native):
            stream = await client.get(f"/api/v1/runs/{row['id']}/events")
            events = [
                json.loads(line[5:])
                for line in stream.text.splitlines()
                if line.startswith("data:")
            ]
            assert events[-1]["type"] == "run_finished"
            assert sum(event["type"] == "tool_result" for event in events) == 1
        assert len(script.requests) == 6
    finally:
        await worker.shutdown()
