"""Initial schema for the native Agent runtime and current product model.

Revision ID: 0001_initial
Revises:
Create Date: 2026-09-23
"""

from collections.abc import Sequence

import sqlalchemy as sa

import app.core.security
from alembic import op

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_conversations",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("actor_id", sa.String(length=128), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("scene", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("next_run_seq", sa.Integer(), nullable=False),
        sa.Column("active_run_id", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "agents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("tools", sa.JSON(), nullable=True),
        sa.Column("skills", sa.JSON(), nullable=True),
        sa.Column("agent_type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_agents_id"), "agents", ["id"], unique=False)
    op.create_table(
        "channels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("config", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_channels_id"), "channels", ["id"], unique=False)
    op.create_table(
        "datasources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("host", sa.String(length=255), nullable=False),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("db_type", sa.String(length=50), nullable=False),
        sa.Column("cluster_key", sa.String(length=255), nullable=False),
        sa.Column("access_level", sa.String(length=50), nullable=False),
        sa.Column("tenant_role", sa.String(length=50), nullable=False),
        sa.Column("user", sa.String(length=255), nullable=True),
        sa.Column("password", app.core.security.EncryptedString(length=512), nullable=True),
        sa.Column("database", sa.String(length=255), nullable=True),
        sa.Column("attributes", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_datasources_id"), "datasources", ["id"], unique=False)
    op.create_table(
        "functions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("draft_code", sa.Text(), nullable=True),
        sa.Column("draft_dependencies", sa.JSON(), nullable=True),
        sa.Column("source_path", sa.String(length=500), nullable=True),
        sa.Column("current_commit_sha", sa.String(length=64), nullable=True),
        sa.Column("release_commit_sha", sa.String(length=64), nullable=True),
        sa.Column("current_release_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["current_release_id"],
            ["function_releases.id"],
            name="fk_functions_current_release_id",
            ondelete="SET NULL",
            use_alter=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_functions_id"), "functions", ["id"], unique=False)
    op.create_index(op.f("ix_functions_slug"), "functions", ["slug"], unique=True)
    op.create_table(
        "knowledge_bases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("source", sa.String(length=50), nullable=True),
        sa.Column("pack_id", sa.String(length=100), nullable=True),
        sa.Column("version", sa.String(length=50), nullable=True),
        sa.Column("repo_subdirectory", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_knowledge_bases_id"), "knowledge_bases", ["id"], unique=False)
    op.create_table(
        "object_audit_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("object_type", sa.String(length=50), nullable=False),
        sa.Column("object_id", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("actor", sa.String(length=255), nullable=False),
        sa.Column("result", sa.String(length=50), nullable=False),
        sa.Column("detail", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_object_audit_logs_id"), "object_audit_logs", ["id"], unique=False)
    op.create_table(
        "pages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("draft_payload", sa.JSON(), nullable=True),
        sa.Column("source_path", sa.String(length=500), nullable=True),
        sa.Column("current_commit_sha", sa.String(length=64), nullable=True),
        sa.Column("release_commit_sha", sa.String(length=64), nullable=True),
        sa.Column("current_release_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["current_release_id"],
            ["page_releases.id"],
            name="fk_pages_current_release_id",
            ondelete="SET NULL",
            use_alter=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pages_id"), "pages", ["id"], unique=False)
    op.create_table(
        "platform_settings",
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("value", sa.JSON(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "services",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("service_type", sa.String(length=50), nullable=False),
        sa.Column("config", sa.JSON(), nullable=True),
        sa.Column("secrets", app.core.security.EncryptedJSON(), nullable=True),
        sa.Column("resource_ref", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_services_id"), "services", ["id"], unique=False)
    op.create_index(op.f("ix_services_resource_ref"), "services", ["resource_ref"], unique=False)
    op.create_table(
        "agent_datasources",
        sa.Column("agent_id", sa.Integer(), nullable=False),
        sa.Column("datasource_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["datasource_id"],
            ["datasources.id"],
        ),
        sa.PrimaryKeyConstraint("agent_id", "datasource_id"),
    )
    op.create_table(
        "agent_runs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("conversation_id", sa.String(length=128), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("client_request_id", sa.String(length=128), nullable=False),
        sa.Column("input_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("actor_id", sa.String(length=128), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("definition", sa.JSON(), nullable=False),
        sa.Column("model_snapshot", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("owner_id", sa.String(length=64), nullable=True),
        sa.Column("lease_until", sa.Float(), nullable=True),
        sa.Column("cancel_requested", sa.Boolean(), nullable=False),
        sa.Column("message_offset", sa.Integer(), nullable=True),
        sa.Column("event_seq", sa.Integer(), nullable=False),
        sa.Column("budget", sa.JSON(), nullable=False),
        sa.Column("pending", sa.JSON(), nullable=True),
        sa.Column("output", sa.Text(), nullable=True),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["agent_conversations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("conversation_id", "client_request_id"),
        sa.UniqueConstraint("conversation_id", "seq"),
    )
    op.create_table(
        "function_releases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("function_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("code_snapshot", sa.Text(), nullable=False),
        sa.Column("dependency_manifest", sa.JSON(), nullable=True),
        sa.Column("release_metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["function_id"], ["functions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "function_id", "version", name="uq_function_releases_function_id_version"
        ),
    )
    op.create_index(op.f("ix_function_releases_id"), "function_releases", ["id"], unique=False)
    op.create_table(
        "knowledge_documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kb_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("content_path", sa.String(length=512), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["kb_id"],
            ["knowledge_bases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_knowledge_documents_id"), "knowledge_documents", ["id"], unique=False)
    op.create_index(
        op.f("ix_knowledge_documents_kb_id"), "knowledge_documents", ["kb_id"], unique=False
    )
    op.create_table(
        "page_build_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("page_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("phase", sa.String(length=50), nullable=True),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("result_summary", sa.Text(), nullable=True),
        sa.Column("error_summary", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["page_id"], ["pages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_page_build_runs_id"), "page_build_runs", ["id"], unique=False)
    op.create_index(op.f("ix_page_build_runs_run_id"), "page_build_runs", ["run_id"], unique=True)
    op.create_table(
        "page_draft_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("page_id", sa.Integer(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("snapshot_payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["page_id"], ["pages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_page_draft_snapshots_id"), "page_draft_snapshots", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_page_draft_snapshots_page_id"), "page_draft_snapshots", ["page_id"], unique=False
    )
    op.create_table(
        "page_owned_functions",
        sa.Column("page_id", sa.Integer(), nullable=False),
        sa.Column("function_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["function_id"], ["functions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["page_id"], ["pages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("page_id", "function_id"),
    )
    op.create_table(
        "page_releases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("page_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("artifact_uri", sa.String(length=500), nullable=True),
        sa.Column("artifact_payload", sa.JSON(), nullable=True),
        sa.Column("release_notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["page_id"], ["pages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("page_id", "version", name="uq_page_releases_page_id_version"),
    )
    op.create_index(op.f("ix_page_releases_id"), "page_releases", ["id"], unique=False)
    op.create_table(
        "service_knowledge_bases",
        sa.Column("service_id", sa.Integer(), nullable=False),
        sa.Column("knowledge_base_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["knowledge_base_id"], ["knowledge_bases.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["service_id"], ["services.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("service_id", "knowledge_base_id"),
    )
    op.create_table(
        "agent_approvals",
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("call_id", sa.String(length=256), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("decision", sa.String(length=32), nullable=False),
        sa.Column("decided_by", sa.String(length=128), nullable=True),
        sa.Column("decided_at", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["agent_runs.id"],
        ),
        sa.PrimaryKeyConstraint("run_id", "call_id"),
    )
    op.create_table(
        "agent_context_snapshots",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("conversation_id", sa.String(length=128), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("source_indices", sa.JSON(), nullable=False),
        sa.Column("source_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("references", sa.JSON(), nullable=False),
        sa.Column("model_name", sa.String(length=256), nullable=False),
        sa.Column("prompt_version", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["agent_conversations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["agent_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "agent_messages",
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("index", sa.Integer(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("sdk_version", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["agent_runs.id"],
        ),
        sa.PrimaryKeyConstraint("run_id", "index"),
    )
    op.create_table(
        "agent_resource_locks",
        sa.Column("resource_key", sa.String(length=512), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("call_id", sa.String(length=256), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["agent_runs.id"],
        ),
        sa.PrimaryKeyConstraint("resource_key"),
    )
    op.create_table(
        "agent_run_events",
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=80), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["agent_runs.id"],
        ),
        sa.PrimaryKeyConstraint("run_id", "seq"),
    )
    op.create_table(
        "agent_tool_calls",
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("call_id", sa.String(length=256), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("arguments", sa.JSON(), nullable=False),
        sa.Column("target", sa.JSON(), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("mutating", sa.Boolean(), nullable=False),
        sa.Column("resource_key", sa.String(length=512), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["agent_runs.id"],
        ),
        sa.PrimaryKeyConstraint("run_id", "call_id"),
    )
    op.create_table(
        "artifact_validations",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("object_type", sa.String(length=32), nullable=False),
        sa.Column("object_id", sa.Integer(), nullable=False),
        sa.Column("revision_id", sa.String(length=64), nullable=False),
        sa.Column("revision_hash", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=True),
        sa.Column("checks", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["agent_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_artifact_validations_object_id"),
        "artifact_validations",
        ["object_id"],
        unique=False,
    )
    op.create_table(
        "function_revisions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("function_id", sa.Integer(), nullable=False),
        sa.Column("revision_hash", sa.String(length=64), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("dependencies", sa.JSON(), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["function_id"], ["functions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["agent_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_function_revisions_function_id"),
        "function_revisions",
        ["function_id"],
        unique=False,
    )
    op.create_table(
        "function_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("function_id", sa.Integer(), nullable=False),
        sa.Column("function_release_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("input_summary", sa.Text(), nullable=True),
        sa.Column("output_summary", sa.Text(), nullable=True),
        sa.Column("output_payload", sa.JSON(), nullable=True),
        sa.Column("error_class", sa.String(length=50), nullable=True),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("runtime_context", sa.JSON(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["function_id"], ["functions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["function_release_id"], ["function_releases.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_function_runs_id"), "function_runs", ["id"], unique=False)
    op.create_index(op.f("ix_function_runs_run_id"), "function_runs", ["run_id"], unique=True)
    op.create_table(
        "page_build_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("build_run_id", sa.Integer(), nullable=False),
        sa.Column("phase", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["build_run_id"], ["page_build_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_page_build_events_id"), "page_build_events", ["id"], unique=False)
    op.create_table(
        "page_compile_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("page_id", sa.Integer(), nullable=False),
        sa.Column("snapshot_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("error_summary", sa.Text(), nullable=True),
        sa.Column("artifact_payload", sa.JSON(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["page_id"], ["pages.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["snapshot_id"], ["page_draft_snapshots.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_page_compile_runs_id"), "page_compile_runs", ["id"], unique=False)
    op.create_index(
        op.f("ix_page_compile_runs_page_id"), "page_compile_runs", ["page_id"], unique=False
    )
    op.create_index(
        op.f("ix_page_compile_runs_run_id"), "page_compile_runs", ["run_id"], unique=True
    )
    op.create_index(
        op.f("ix_page_compile_runs_snapshot_id"), "page_compile_runs", ["snapshot_id"], unique=False
    )
    op.create_table(
        "page_revisions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("page_id", sa.Integer(), nullable=False),
        sa.Column("revision_hash", sa.String(length=64), nullable=False),
        sa.Column("files", sa.JSON(), nullable=False),
        sa.Column("bindings", sa.JSON(), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["page_id"], ["pages.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["agent_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_page_revisions_page_id"), "page_revisions", ["page_id"], unique=False)
    op.create_table(
        "schedules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("target_type", sa.String(length=20), nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=True),
        sa.Column("schedule_type", sa.String(length=20), nullable=False),
        sa.Column("cron_expression", sa.String(length=255), nullable=True),
        sa.Column("interval_seconds", sa.Integer(), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("datasource_id", sa.Integer(), nullable=True),
        sa.Column("function_id", sa.Integer(), nullable=True),
        sa.Column("function_release_id", sa.Integer(), nullable=True),
        sa.Column("input_payload", sa.JSON(), nullable=True),
        sa.Column("input_prompt", sa.Text(), nullable=True),
        sa.Column("next_run_at", sa.DateTime(), nullable=True),
        sa.Column("last_run_at", sa.DateTime(), nullable=True),
        sa.Column("max_retries", sa.Integer(), nullable=False),
        sa.Column("retry_backoff_seconds", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["datasource_id"],
            ["datasources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["function_id"],
            ["functions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["function_release_id"],
            ["function_releases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_schedules_id"), "schedules", ["id"], unique=False)
    op.create_table(
        "skill_drafts",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("actor_id", sa.String(length=128), nullable=False),
        sa.Column("revision", sa.String(length=64), nullable=False),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=True),
        sa.Column("updated_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["agent_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "page_compilations",
        sa.Column("validation_id", sa.String(length=64), nullable=False),
        sa.Column("html", sa.Text(), nullable=False),
        sa.Column("artifact_hash", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["validation_id"],
            ["artifact_validations.id"],
        ),
        sa.PrimaryKeyConstraint("validation_id"),
    )
    op.create_table(
        "schedule_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("schedule_id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("trigger_type", sa.String(length=20), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("max_retries", sa.Integer(), nullable=False),
        sa.Column("correlation_id", sa.String(length=128), nullable=True),
        sa.Column("target_type", sa.String(length=20), nullable=True),
        sa.Column("runtime_run_id", sa.String(length=64), nullable=True),
        sa.Column("runtime_status", sa.String(length=50), nullable=True),
        sa.Column("conversation_id", sa.String(length=128), nullable=True),
        sa.Column("error_summary", sa.Text(), nullable=True),
        sa.Column("output_summary", sa.Text(), nullable=True),
        sa.Column("output_payload", sa.JSON(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["agent_conversations.id"],
        ),
        sa.ForeignKeyConstraint(["schedule_id"], ["schedules.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id"),
    )
    op.create_index(op.f("ix_schedule_runs_id"), "schedule_runs", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_schedule_runs_id"), table_name="schedule_runs")
    op.drop_table("schedule_runs")
    op.drop_table("page_compilations")
    op.drop_table("skill_drafts")
    op.drop_index(op.f("ix_schedules_id"), table_name="schedules")
    op.drop_table("schedules")
    op.drop_index(op.f("ix_page_revisions_page_id"), table_name="page_revisions")
    op.drop_table("page_revisions")
    op.drop_index(op.f("ix_page_compile_runs_snapshot_id"), table_name="page_compile_runs")
    op.drop_index(op.f("ix_page_compile_runs_run_id"), table_name="page_compile_runs")
    op.drop_index(op.f("ix_page_compile_runs_page_id"), table_name="page_compile_runs")
    op.drop_index(op.f("ix_page_compile_runs_id"), table_name="page_compile_runs")
    op.drop_table("page_compile_runs")
    op.drop_index(op.f("ix_page_build_events_id"), table_name="page_build_events")
    op.drop_table("page_build_events")
    op.drop_index(op.f("ix_function_runs_run_id"), table_name="function_runs")
    op.drop_index(op.f("ix_function_runs_id"), table_name="function_runs")
    op.drop_table("function_runs")
    op.drop_index(op.f("ix_function_revisions_function_id"), table_name="function_revisions")
    op.drop_table("function_revisions")
    op.drop_index(op.f("ix_artifact_validations_object_id"), table_name="artifact_validations")
    op.drop_table("artifact_validations")
    op.drop_table("agent_tool_calls")
    op.drop_table("agent_run_events")
    op.drop_table("agent_resource_locks")
    op.drop_table("agent_messages")
    op.drop_table("agent_context_snapshots")
    op.drop_table("agent_approvals")
    op.drop_table("service_knowledge_bases")
    op.drop_index(op.f("ix_page_releases_id"), table_name="page_releases")
    op.drop_table("page_releases")
    op.drop_table("page_owned_functions")
    op.drop_index(op.f("ix_page_draft_snapshots_page_id"), table_name="page_draft_snapshots")
    op.drop_index(op.f("ix_page_draft_snapshots_id"), table_name="page_draft_snapshots")
    op.drop_table("page_draft_snapshots")
    op.drop_index(op.f("ix_page_build_runs_run_id"), table_name="page_build_runs")
    op.drop_index(op.f("ix_page_build_runs_id"), table_name="page_build_runs")
    op.drop_table("page_build_runs")
    op.drop_index(op.f("ix_knowledge_documents_kb_id"), table_name="knowledge_documents")
    op.drop_index(op.f("ix_knowledge_documents_id"), table_name="knowledge_documents")
    op.drop_table("knowledge_documents")
    op.drop_index(op.f("ix_function_releases_id"), table_name="function_releases")
    op.drop_table("function_releases")
    op.drop_table("agent_runs")
    op.drop_table("agent_datasources")
    op.drop_index(op.f("ix_services_resource_ref"), table_name="services")
    op.drop_index(op.f("ix_services_id"), table_name="services")
    op.drop_table("services")
    op.drop_table("platform_settings")
    op.drop_index(op.f("ix_pages_id"), table_name="pages")
    op.drop_table("pages")
    op.drop_index(op.f("ix_object_audit_logs_id"), table_name="object_audit_logs")
    op.drop_table("object_audit_logs")
    op.drop_index(op.f("ix_knowledge_bases_id"), table_name="knowledge_bases")
    op.drop_table("knowledge_bases")
    op.drop_index(op.f("ix_functions_slug"), table_name="functions")
    op.drop_index(op.f("ix_functions_id"), table_name="functions")
    op.drop_table("functions")
    op.drop_index(op.f("ix_datasources_id"), table_name="datasources")
    op.drop_table("datasources")
    op.drop_index(op.f("ix_channels_id"), table_name="channels")
    op.drop_table("channels")
    op.drop_index(op.f("ix_agents_id"), table_name="agents")
    op.drop_table("agents")
    op.drop_table("agent_conversations")
    # ### end Alembic commands ###
