global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: prometheus-demo
    static_configs:
      - targets: ["prometheus-demo:9090"]

  - job_name: cadvisor-demo
    static_configs:
      - targets: ["cadvisor-demo:8080"]
